AinAlfahd/Models/ShippingBatch.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace AinAlfahd.Models
{
    public class ShippingBatch
    {
        public int ShippingBatchId { get; set; }
        public DateTime? ShippingDate { get; set; }
        public DateTime? ArrivelDate { get; set; }
        public DateTime? EntryDate { get; set; }
        public decimal? batchCostUS { get; set; }   
        public string? Notes { get; set; }
        public decimal? SellingIQ { get; set; }
        public int? ReciptsNu { get; set; }
        
        [ForeignKey("ShippingTypes")]
        public int? ShippingTypeId { get; set; }
        public ShippingTypes? ShippingTypes { get; set; }
        [JsonIgnore]
        public List<Reciept>? Recipts { get; set; }
    }
}

AinAlfahd/Areas/Admin/Controllers/ShippingBatchController.cs
using AinAlfahd.Data;
using AinAlfahd.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AinAlfahd.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ShippingBatchController : Controller
    {
        MasterDBContext dBContext;
        public ShippingBatchController(MasterDBContext dBContext)
        {
            this.dBContext = dBContext;
        }

        public async Task<IActionResult> Index()
        {
            var shippingBatchs = await dBContext.ShippingBatchs.Include(sh => sh.ShippingTypes).ToListAsync();
            return View(shippingBatchs);
        }

        public async Task<IActionResult> AddShippingBatch(int? iid)
        {
            var shipp = await dBContext.ShippingBatchs.Include(s => s.ShippingTypes).FirstOrDefaultAsync(s => s.ShippingBatchId == iid);
            var types = await dBContext.ShippingTypes.ToListAsync();
            ViewBag.shippingType = types.Select(a => new SelectListItem
            {
                Value = a.ShippingTypeId.ToString(),
                Text = a.Description
            }).ToList();

            if (shipp != null)
                return View(shipp);

            return View(new ShippingBatch());
        }

        public async Task<IActionResult> SaveShipping(ShippingBatch model)
        {
            if (!ModelState.IsValid)
            {
                TempData["msg"] = "تحقق من البيانات المدخلة من فضلك";
                return RedirectToAction("AddShippingBatch");
            }

            if (model.ShippingBatchId == 0)
            {
                var shipp = new ShippingBatch
                {
                    ArrivelDate = model.ArrivelDate,
                    EntryDate = model.EntryDate,
                    ShippingDate = model.ShippingDate,
                    batchCostUS = model.batchCostUS,
                    ShippingTypeId = model.ShippingTypeId,
                };

                await dBContext.ShippingBatchs.AddAsync(shipp);
                await dBContext.SaveChangesAsync();
                TempData["msg"] = "تم الحفظ بنجاح";
                return RedirectToAction("Index");
            }
            else if (model.ShippingBatchId > 0)
            {
                var shipp = await dBContext.ShippingBatchs.FindAsync(model.ShippingBatchId);
                shipp.ArrivelDate = model.ArrivelDate;
                shipp.EntryDate = model.EntryDate;
                shipp.ShippingDate = model.ShippingDate;
                shipp.ShippingTypeId = model.ShippingTypeId;
                shipp.batchCostUS = model.batchCostUS;

                dBContext.ShippingBatchs.Update(shipp);
                await dBContext.SaveChangesAsync();
                TempData["msg"] = "تم الحفظ بنجاح";
                return RedirectToAction("Index");
            }

            TempData["msg"] = "حدث خطأ ما يرجى المحاولة مجددا !";
            return RedirectToAction("Index");

        }

        public async Task<IActionResult> DeleteData(int iiid)
        {
            var shipp = await dBContext.ShippingBatchs.FindAsync(iiid);

            if (shipp == null)
            {
                TempData["msg"] = "حدث خطأ ما يرجى المحاولة مجددا !";
                return RedirectToAction("Index");
            }

            var receipts = dBContext.Reciepts.Where(r => r.ShippingBatchId == iiid).ToList();
            foreach (var receipt in receipts)
            {
                receipt.ShippingBatchId = null;
            }
            await dBContext.SaveChangesAsync();

            dBContext.ShippingBatchs.Remove(shipp);
            await dBContext.SaveChangesAsync();
            TempData["msg"] = "تم الحذف بنجاح !";
            return RedirectToAction("Index");

        }


    }
}

AinAlfahd/Areas/Admin/Views/ShippingBatch/AddShippingBatch.cshtml
@using AinAlfahd.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model ShippingBatch

@{
    ViewData["Title"] = "AddShippingBatch";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="container my-5">
    <h2 class="bg-gradient text-light p-3 text-center rounded" style="background: linear-gradient(90deg, #007BFF, #0056b3);">
        إضافة بيانات جديدة
    </h2>

    <div class="row justify-content-center mt-4">
        <form class="col-md-8 p-4 border rounded shadow-lg" style="background-color: #f9f9f9;" asp-action="SaveShipping" method="post">
            <input hidden asp-for="@Model.ShippingBatchId" class="form-control border-primary" />

            <div class="mb-3">
                <label asp-for="@Model.ShippingDate" class="form-label fw-bold">تاريخ الشحن من دبي</label>
                <input type="text" asp-for="ShippingDate" class="form-control border-primary"
                       value="@(Model.ShippingDate?.ToString("yyyy-MM-dd") ?? DateTime.Now.ToString(" yyyy-MM-dd"))" />

                <span asp-validation-for="@Model.ShippingDate" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="@Model.ArrivelDate" class="form-label fw-bold">تاريخ وصول الوجبة</label>
                <input type="text" asp-for="@Model.ArrivelDate" class="form-control border-success"
                       value="@(Model.ArrivelDate?.ToString("yyyy-MM-dd") ?? DateTime.Now.ToString(" yyyy-MM-dd"))" />
                <span asp-validation-for="@Model.ArrivelDate" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="@Model.EntryDate" class="form-label fw-bold">تاريخ ادخال الوجبة</label>
                <input type="text" asp-for="@Model.EntryDate" class="form-control border-warning"
                       value="@(Model.EntryDate?.ToString("yyyy-MM-dd") ?? DateTime.Now.ToString(" yyyy-MM-dd"))" />
                <span asp-validation-for="@Model.EntryDate" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="@Model.ShippingTypeId" class="form-label fw-bold">نوع الشحن</label>
                <select asp-for="@Model.ShippingTypeId" class="form-control border-info" asp-items="@ViewBag.shippingType"></select>
                <span asp-validation-for="@Model.ShippingTypeId" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="@Model.batchCostUS" class="form-label fw-bold">التكلفة بالدولار</label>
                <input asp-for="@Model.batchCostUS" class="form-control border-danger" />
                <span asp-validation-for="@Model.batchCostUS" class="text-danger"></span>
            </div>

            <div class="text-center">
                <button type="submit" class="btn btn-primary px-5 py-2">
                    <i class="fas fa-save"></i> حفظ البيانات
                </button>
            </div>
        </form>
    </div>
</div>

AinAlfahd/Areas/Admin/Views/ShippingBatch/Index.cshtml
@using AinAlfahd.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<ShippingBatch>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="d-flex justify-content-between flex-row-reverse">
    <h1 class="text-center my-4" style="color: #4CAF50; font-weight: bold;">الوجبات</h1>
    <a class="btn btn-warning m-3" asp-area="Admin" asp-controller="ShippingBatch" asp-action="AddShippingBatch">
        إضافة
    </a>
</div>
<div class="text-black-50 text-center m-3">@TempData["msg"]</div>
<div class="border rounded shadow-lg" style="max-height: 38vh; overflow-y: auto; border-color: #4CAF50;">
    <table class="table table-hover table-bordered mb-0">
        <thead style="position: sticky; top: 0; background: linear-gradient(90deg, #4CAF50, #2E7D32); color: #fff; z-index: 999;">
            <tr>
                <th class="text-center" style="width: 20%;">تعديلات</th>
                <th class="text-end">التكلفة بالدولار</th>
                <th class="text-end">نوع الشحن</th>
                <th class="text-end">تاريخ ادخال الوجبة</th>
                <th class="text-end">تاريخ وصول الوجبة</th>
                <th class="text-end">تاريخ الشحن من دبي</th>
            </tr>
        </thead>
        <tbody class="foooor" style="background-color: #F1F8E9;">
            @foreach (var shipping in Model)
            {
                <tr>
                    <td class="d-flex justify-content-center">
                        <a class="btn btn-outline-primary btn-sm mx-1" asp-action="AddShippingBatch" asp-route-iid="@shipping.ShippingBatchId">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-outline-danger btn-sm mx-1" asp-action="DeleteData" asp-route-iiid="@shipping.ShippingBatchId">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                    @if(@shipping.batchCostUS != null)
                    {
                        <td class="text-end" style="color: #388E3C; font-weight: bold;">@shipping.batchCostUS$</td>
                    }
                    else
                    {
                        <td class="text-end" style="color: #388E3C; font-weight: bold;">@shipping.batchCostUS</td>
                    }
                    
                    <td class="text-end" style="color: #388E3C; font-weight: bold;">@shipping.ShippingTypes.Description</td>
                    <td class="text-end" style="color: #388E3C; font-weight: bold;">@shipping.EntryDate?.ToString("yyyy-MM-dd")</td>
                    <td class="text-end" style="color: #388E3C; font-weight: bold;">@shipping.ArrivelDate?.ToString("yyyy-MM-dd")</td>
                    <td class="text-end" style="color: #388E3C; font-weight: bold;">@shipping.ShippingDate?.ToString("yyyy-MM-dd")</td>
                </tr>
            }
        </tbody>
    </table>
</div>