AinAlfahd/Areas/Admin/Controllers/ReciptController.cs
using AinAlfahd.Data;
using AinAlfahd.Models;
using AinAlfahd.ModelsDTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Project;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;

namespace AinAlfahd.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ReciptController : Controller
    {
        MasterDBContext dBContext;

        public ReciptController(MasterDBContext dBContext)
        {
            this.dBContext = dBContext;
        }

        public async Task<IActionResult> Index()
        {
            var recipts = await dBContext.Reciepts.Where(c => c.CurrentState == true).Include(r => r.Customer).Include(r => r.ShippingBatch).OrderBy(r => r.RecieptDate).ToListAsync();
            return View(recipts);
        }

        public async Task<IActionResult> AddReciept(int? id)
        {
            var customers = await dBContext.Customers.Include(c => c.CustomerServices)
                .ThenInclude(cs => cs.Service)
                .Where(c => c.CustomerServices.Any(cs => cs.Service.Description == "Air Shipping"))
                .ToListAsync();

            var shippingBatch = await dBContext.ShippingBatchs.ToListAsync();
 
            ViewBag.shippingBatchs = shippingBatch.Select(c => new SelectListItem
            {
                Value = c.ShippingBatchId.ToString(),
                Text = c.ArrivelDate?.ToString("yyyy-MM-dd"),
            }).ToList();

            var excgange = await dBContext.Exchanges.FirstOrDefaultAsync();

            ViewBag.ex = excgange.ExchangeRate;
            ViewBag.Customer = customers.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.CustName,
            }).ToList();

            var reciepts = await dBContext.Reciepts.ToListAsync();

            if(id.HasValue && id != 0)
            {
                var reciept = await dBContext.Reciepts.FindAsync(id);
                return View(reciept);
            }

            return View(new Reciept());
        }

        [HttpPost]
        public async Task<IActionResult> SaveRe(RecirptDto model)
        {
            if(model.RecieptDate > DateTime.Now)
            {
                TempData["error"] = "يرجى التحقق من التاريخ المدخل!";
                return RedirectToAction("AddReciept");
            }

            if (!ModelState.IsValid)
            {
                TempData["error"] = "البيانات المدخلة غير صحيحة الرجاء إعادة المحاولة !";
                return RedirectToAction("AddReciept");
            }
            if(model.RecieptId == 0)
            {
                var reci = await dBContext.Reciepts.Where(r => r.CustomerId == model.CustomerId & r.Weight == model.Weight & r.RecieptDate == model.RecieptDate).FirstOrDefaultAsync();
                if (reci != null)
                {
                    TempData["error"] = "الوصل موجود مسبقا  !";
                    return RedirectToAction("AddReciept");
                }
                var re = new Reciept
                {
                    Cost = model.Cost,
                    Currency = "$",
                    CustomerId = model.CustomerId,
                    DisCount = model.DisCount,
                    InsertBy = "Anyy one",
                    IsFinanced = model.IsFinanced,
                    InsertDate = DateTime.Now,
                    SellingCurrency = "IQ",
                    RecieptDate = model.RecieptDate,
                    SellingDisCount = model.SellingDisCount,
                    SellingPrice = model.SellingPrice,
                    Weight = model.Weight,
                    TotalPriceFromCust = Math.Ceiling(model.TotalPriceFromCust),
                    CurrentState = model.CurrentState,
                    Notes = model.Notes,
                    ShippingBatchId = model.ShippingBatchId,
                };

                await dBContext.Reciepts.AddAsync(re);
                await dBContext.SaveChangesAsync();
                TempData["error"] = "تم الحفظ بنجاح  !";
                return RedirectToAction("AddReciept");
            }
            else
            {
                var rec = await dBContext.Reciepts.FindAsync(model.RecieptId);
                if (rec != null)
                {
                    rec.Cost = model.Cost;
                    rec.Currency = "$";
                    rec.CustomerId = model.CustomerId;
                    rec.DisCount = model.DisCount;
                    rec.InsertBy = "Anyy one";
                    rec.IsFinanced = model.IsFinanced;
                    rec.InsertDate = DateTime.Now;
                    rec.SellingCurrency = "IQ";
                    rec.RecieptDate = model.RecieptDate;
                    rec.SellingDisCount = model.SellingDisCount;
                    rec.SellingPrice = model.SellingPrice;
                    rec.Weight = model.Weight;
                    rec.TotalPriceFromCust = Math.Ceiling(model.TotalPriceFromCust);
                    rec.CurrentState = true;

                    dBContext.Reciepts.Update(rec);
                    await dBContext.SaveChangesAsync();
                    TempData["msg"] = "تم التعديل بنجاح  !";
                    return RedirectToAction("Index");
                }
                else {
                    TempData["error"] = "خطأ أثناء تعديل البيانات !";
                    return RedirectToAction("AddReciept");
                }

            }
            
        }

        public async Task<IActionResult> DeleteData(int id)
        {
            var rec = await dBContext.Reciepts.FindAsync(id);
            if (rec != null) {

                rec.CurrentState = false;
                await dBContext.SaveChangesAsync();
                TempData["msg"] = "تم الحذف بنجاح !";
                return RedirectToAction("Index");
            }
            TempData["msg"] = "حدث خطأ اثناء حذف السجل !";
            return RedirectToAction("Index");
        }

        [HttpGet("/Admin/Customer/SerachAboutCust/{word}")]
        public async Task<IActionResult> SerachAboutCust(string word)
        {
            var costomers = await dBContext.Customers.Where(c => c.CustMob.Contains(word) || c.CustName.Contains(word) 
            || c.Id.ToString() == word).ToListAsync();
            return Ok(costomers);
        }

        [HttpGet("/Admin/Customer/SerachAboutCust1/{word}")]
        public async Task<IActionResult> SerachAboutCust1(string word)
        {
            var costomers = await dBContext.Customers.Where(c => c.CustMob.Contains(word) || c.CustName.Contains(word)
            || c.Id.ToString() == word).ToListAsync();
            return Ok(costomers);
        }

        [HttpGet("/Admin/Recipt/SerachByDate/{from}/{to}")]
        public async Task<IActionResult> SerachByDate(string from, string to)
        {
            var recipts = await dBContext.Reciepts
                .Where(c => c.CurrentState == true & c.RecieptDate >= DateTime.Parse(from) & c.RecieptDate <= DateTime.Parse(to))
                .OrderBy(r => r.RecieptDate)
                .Include(r => r.Customer).ToListAsync();


            return Ok(recipts);
        }
    }

    }

AinAlfahd/Areas/Admin/Views/Recipt/Index.cshtml
@using AinAlfahd.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Reciept>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@{
    decimal cost = 0;
    decimal f = 0;
    int countOfLines = 0;
}

<style>
    .info-card {
       
        background-color: #f9f9f9;
        border: 1px solid #ddd;
        border-radius: 8px;
        padding: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        max-width: 3500px;
        margin: auto;
    }

    .value {
        font-size: 1.2em;
        font-weight: bold;
        color: #333;
        o-card

    {
        display: flex;
        justify-content: space-around;
        align-items: center;
    }

    .currency {
        font-size: 0.9em;
        color: #555;
    }
</style>


<div class="container">
    <div class="position-sticky" style="top: 0; background-color: white; z-index: 1000;">
        <h2 class="mb-4 p-1 text-end"> الفواتير </h2>
        <h4 class="text-center text-danger">@TempData["msg"]</h4>
        <hr />
    </div>
    <div>
         <button onclick="print()">print</button>
     </div>

    <div class="mb-3 col-10">
        <div class="mb-3 d-flex align-items-end flex-column">
            <label for="fromDate" class="form-label pe-1 text-dark fw-bold text-st">من تاريخ</label>
            <input id="FromDate" type="text" id="fromDate" value="@DateTime.Now.ToString("yyyy-MM-dd")" class="form-control" />
        </div>

        <div class="mb-3 d-flex align-items-end flex-column">
            <label for="to" class="form-label pe-1 text-dark  fw-bold text-st">الى تاريخ</label>
            <input id="ToDate" type="text" id="fromDate" value="@DateTime.Now.ToString("yyyy-MM-dd")" class="form-control" />
        </div>
        <div class="d-flex justify-content-center">
            <button class="btn btn-info col-4" onclick="SearchByDate()">بحث</button>
        </div>
    </div>

    <hr />


    <div class="border border-dark" style="max-height: 38vh; overflow-y: auto;">
        <table class="table table-bordered table-striped">
            <thead class="thead-light" style="position: sticky; top: 0; background-color: gray; z-index: 999;">
                <tr>
                    <th class="text-end m-1" style="background-color: gray;">تعديلات</th>
                    <th class="text-end m-1" style="background-color: gray;">تاريخ الوجبة</th>
                    <th class="text-end m-1" style="background-color: gray;">حالة الدفع</th>
                    <th class="text-end m-1 "style="background-color: gray;">المبلغ</th>
                    <th class="text-end m-1" style="background-color: gray;">الكلفة</th>
                    <th class="text-end m-1" style="background-color: gray;">الوزن</th>
                    <th class="text-end m-1" style="background-color: gray;">اسم العميل</th>
                    <th class="text-end m-1" style="background-color: gray;">تاريخ الوصل</th>
                    <th class="text-end m-1" style="background-color: gray;">رقم الوصل</th>
                </tr>
            </thead>
            <tbody class="foooor">
                @foreach (var receipt in Model)
                {
                    cost += receipt.Cost;
                    f += receipt.TotalPriceFromCust;
                    countOfLines++;

                    <tr>
                        <td class="d-flex justify-content-center">
                            <a class="btn btn-primary" asp-action="AddReciept" asp-route-id="@receipt.RecieptId"><i class="fas fa-edit"></i></a>
                            <a class="btn ms-1 btn-danger" asp-action="DeleteData" asp-route-id="@receipt.RecieptId"><i class="fas fa-trash"></i></a>
                        </td>
                        <td class="text-end m-1">@(receipt.ShippingBatch?.ArrivelDate ?? null)</td>
                        @{
                            if (@receipt.IsFinanced)
                            {
                                            <td class="text-end m-1">مدفوعة</td>
                            }else{
                                            <td class="text-end m-1">غير مدفوعة</td>
                            }
                        }
                        <td class="text-end m-1">@receipt.TotalPriceFromCust.ToString("N0") IQ</td>
                        <td class="text-end m-1">@receipt.Cost $</td>
                        <td class="text-end m-1">@receipt.Weight Kg</td>
                        <td class="text-end m-1">@receipt.Customer.CustName</td>
                        <td class="text-end m-1">@receipt.RecieptDate.ToString("yyyy-MM-dd")</td>
                        <td class="text-end m-1">@receipt.RecieptId</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<br />
<div class="info-card row col-12">
    <div class="value col-4">
        <span class="currency text-danger">Cost :</span> <span id="totalCost">@cost.ToString("N0")</span> <span class="currency text-success">$</span>
    </div>
    <div class="value col-4">
        <span  class="currency text-danger">Profits :</span> <span id="totalProfits">@f.ToString("N0")</span> <span class="currency text-success">IQ</span>
    </div>
    <div class="value col-4">
        <span class="currency text-danger">Lines: <span id="totalLines">@countOfLines</span></span>
    </div>
</div>

@section Scripts{

    <script>
        function getCloseTenUp(value) {
            const magnitude = Math.pow(10, Math.floor(Math.log10(value) - 1));
            return Math.ceil(value / magnitude) * magnitude;
        }

        $(document).ready(function () {
            console.log("dfgedhdf");
        })

        function SearchByDate() {
            const from = $('#FromDate').val();
            const to = $('#ToDate').val();

            const apiUrl = `/Admin/Recipt/SerachByDate/${encodeURIComponent(from)}/${encodeURIComponent(to)}`;

            $.ajax({
                url: apiUrl,
                type: 'GET',
                success: function (data) {
                    console.log(data);
                    const tbody = $('.foooor');
                    tbody.empty();
                    var co = 0;
                    var pro = 0;
                    var li = 0;

                    $('#totalCost').text('');
                    $('#totalProfits').text('');
                    $('#totalLines').text('');


                    if (Array.isArray(data) && data.length > 0) {

                        data.forEach(rec => {
                            tbody.append(`
                                        <tr>
                                                              <td class="text-end m-1">
                            <a class="btn btn-primary" href="@Url.Action("AddReciept", "Recipt")?id=${rec.recieptId}">تعديل</a>
                                    <a class="btn ms-1 btn-danger" href="@Url.Action("DeleteData", "Recipt")?id=${rec.recieptId}">حذف</a>
                                                              </td>

                                                            <td class="text-end m-1">${rec.isFinanced}</td>
                                                             <td class="text-end m-1">${Number(rec.totalPriceFromCust).toLocaleString()} IQ</td>
                                                            <td class="text-end m-1">${rec.cost}</td>
                                                            <td class="text-end m-1">${rec.weight}</td>
                                                            <td class="text-end m-1">${rec.customer.custName}</td>
                                                            <td class="text-end m-1">${new Date(rec.recieptDate).toLocaleDateString()}</td>

                                                            <td class="text-end m-1">${rec.recieptId}</td>
                                        </tr>
                                     `);

                            co += rec.cost;
                            pro += rec.totalPriceFromCust;
                            li++;
                        });

                        $('#totalCost').text('Cost :' + co.toLocaleString())
                        $('#totalProfits').text(getCloseTenUp(pro).toLocaleString());
                        $('#totalLines').text(li);


                    } 
                },
                error: function (xhr, status, error) {
                    console.error(`Error: ${xhr.status} - ${xhr.statusText}`);
                    alert('لم يتم العثور على بيانات العميل.');
                }
            });
        }

        function print() {

            let x = 40;

            var url = `${window.origin}/api/Reciept/GeneratePdf`;

            if (x !== undefined && x !== null) {
                url += `/${x}`;
            }

            window.location.href = url;
        }


    </script>
}